In [13]:
from my_functions import *
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
x, y = load_data("data/student-mat.csv")

C:\Users\Admin\Desktop\Project\my_functions.py:39: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_num[column] = non_num[column].apply(lambda x: column[0].lower() + "_" + x)


In [3]:
x

school  sex  age  higher  activities  G1  G2  m_at_home  m_health  \
0         0    0   18       1           0   5   6          1         0   
1         0    0   17       1           0   5   5          1         0   
2         0    0   15       1           0   7   8          1         0   
3         0    0   15       1           1  15  14          0         1   
4         0    0   16       1           0   6  10          0         0   
..      ...  ...  ...     ...         ...  ..  ..        ...       ...   
390       1    1   20       1           0   9   9          0         0   
391       1    1   17       1           0  14  16          0         0   
392       1    1   21       1           0  10   8          0         0   
393       1    1   18       1           0  11  12          0         0   
394       1    1   19       1           0   8   9          0         0   

     m_other  m_services  f_at_home  f_health  f_other  f_services  
0          0           0          0         0        0           0  
1          0           0          0         0        1           0  
2          0           0          0         0        1           0  
3          0           0          0         0        0           1  
4          1           0          0         0        1           0  
..       ...         ...        ...       ...      ...         ...  
390        0           1          0         0        0           1  
391        0           1          0         0        0           1  
392        1           0          0         0        1           0  
393        0           1          0         0        1           0  
394        1           0          1         0        0           0  

[395 rows x 15 columns]

In [4]:
y

0       6
1       6
2      10
3      15
4      10
       ..
390     9
391    16
392     7
393    10
394     9
Name: G3, Length: 395, dtype: int64

In [5]:
x, y  = pd_to_np(x,y)

In [6]:
x

array([[ 0.,  0., 18., ...,  0.,  0.,  0.],
       [ 0.,  0., 17., ...,  0.,  1.,  0.],
       [ 0.,  0., 15., ...,  0.,  1.,  0.],
       ...,
       [ 1.,  1., 21., ...,  0.,  1.,  0.],
       [ 1.,  1., 18., ...,  0.,  1.,  0.],
       [ 1.,  1., 19., ...,  0.,  0.,  0.]])

In [7]:
y

array([ 6.,  6., 10., 15., 10., 15., 11.,  6., 19., 15.,  9., 12., 14.,
       11., 16., 14., 14., 10.,  5., 10., 15., 15., 16., 12.,  8.,  8.,
       11., 15., 11., 11., 12., 17., 16., 12., 15.,  6., 18., 15., 11.,
       13., 11., 12., 18., 11.,  9.,  6., 11., 20., 14.,  7., 13., 13.,
       10., 11., 13., 10., 15., 15.,  9., 16., 11., 11.,  9.,  9., 10.,
       15., 12.,  6.,  8., 16., 15., 10.,  5., 14., 11., 10., 10., 11.,
       10.,  5., 12., 11.,  6., 15., 10.,  8.,  6., 14., 10.,  7.,  8.,
       18.,  6., 10., 14., 10., 15., 10., 14.,  8.,  5., 17., 14.,  6.,
       18., 11.,  8., 18., 13., 16., 19., 10., 13., 19.,  9., 16., 14.,
       13.,  8., 13., 15., 15., 13., 13.,  8., 12., 11.,  9.,  0., 18.,
        0.,  0., 12., 11.,  0.,  0.,  0.,  0., 12., 15.,  0.,  9., 11.,
       13.,  0., 11.,  0., 11.,  0., 10.,  0., 14., 10.,  0., 12.,  8.,
       13., 10., 15., 12.,  0.,  7.,  0., 10.,  7., 12., 10., 16.,  0.,
       14.,  0., 16., 10.,  0.,  9.,  9., 11.,  6.,  9., 11.,  8

In [8]:
def normalize(x):
    """

    Performs feature scaling in the range [0,1] by division of each feature by its maximum value.

    Parameters:
        x (ndarray): Training set (features of students)

    Returns:
        x (ndarray): Training set exposed to feature scaling (input to the model)
    """

    x = x.astype('float64')
    for column in range(x.shape[1]):
        x[:, column] = x[:, column] / x[:, column].max()

    return x

In [9]:
x = normalize(x)
x

array([[0.        , 0.        , 0.81818182, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.77272727, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.68181818, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 1.        , 0.95454545, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.81818182, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.86363636, ..., 0.        , 0.        ,
        0.        ]])

In [10]:
type(x)

numpy.ndarray

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7)

In [16]:
x_train

array([[0.        , 1.        , 0.68181818, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.86363636, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.72727273, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.68181818, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.72727273, ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.72727273, ..., 0.        , 1.        ,
        0.        ]])

In [17]:
len(x_train)

276

In [18]:
len(y_train)

276

In [19]:
# LinearRegression model
model = LinearRegression()

In [25]:
model.fit(x_train, y_train)

LinearRegression()

In [26]:
r_sq = model.score(x_test, y_test)

In [27]:
r_sq

0.7496652171876785