In [1]:
from my_functions import *
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
def new_student(x):
    """
    
    Creates an array of features for a new student. 
    
    Parameters:
        x (pandas dataframe): Shape(m,n) Training set to the model. Defines the features for a new student
        
    Returns:
        new (pandas dataframe): 
    """
    
    new_data = {}
    for column in x.columns:
        if x[column].dtype == "object":
            inp = input("Please write the " + column + " of a student (" + str(x[column].unique()) + "): ")
            while inp not in x[column].unique():
                print("Invalid feature! Please try again!")
                inp = input("Please write the " + column + " of a student (" + str(x[column].unique()) + "): ")
                
        elif column == "age":
            while True:
                try:
                    inp = int(input("Please write the " + column +" of a student (from " + str(15) + " to " + str(25) + "): "))
                    while inp < 15 or inp > 25:
                        print("Invalid feature! Please try again!")
                        inp = int(input("Please write the " + column +" of a student (from " + str(15) + " to " + str(25) + "): "))
                except ValueError: 
                    print("Value Error for age! Please try again!")
                    continue
                
                if inp >= 15 or inp <= 25:
                    break
        
        
        elif column == "G1" or column == "G2":
            while True:
                try:
                    inp = int(input("Please write the " + column +" of a student (from " + str(0) + " to " + str(20) + "): "))
                    while inp < 0 or inp > 20:
                        print("Invalid grade! Please try again!")
                        inp = int(input("Please write the " + column +" of a student (from " + str(0) + " to " + str(20) + "): "))
                except ValueError:
                    print("Value Error for grade! Please try again!")
                    continue
                if inp >= 0 or inp <= 20:
                    break
                    
                    
        new_data[column] = inp
    
    new = pd.DataFrame(new_data, index=[0])
        
        
            
            
        
        
        
    return new

In [3]:
x, y = load_data("data/student-mat.csv")
x

school sex  age      Mjob      Fjob higher activities  G1  G2
0       GP   F   18   at_home   teacher    yes         no   5   6
1       GP   F   17   at_home     other    yes         no   5   5
2       GP   F   15   at_home     other    yes         no   7   8
3       GP   F   15    health  services    yes        yes  15  14
4       GP   F   16     other     other    yes         no   6  10
..     ...  ..  ...       ...       ...    ...        ...  ..  ..
390     MS   M   20  services  services    yes         no   9   9
391     MS   M   17  services  services    yes         no  14  16
392     MS   M   21     other     other    yes         no  10   8
393     MS   M   18  services     other    yes         no  11  12
394     MS   M   19     other   at_home    yes         no   8   9

[395 rows x 9 columns]

In [4]:
x["school"].unique()

array(['GP', 'MS'], dtype=object)

In [17]:
new_student = new_student(x)

UnboundLocalError: local variable 'inp' referenced before assignment

In [18]:
new_student

<function my_functions.new_student(x)>

In [7]:
new_student

school sex  age     Mjob      Fjob higher activities  G1  G2
0     GP   M   25  teacher  services    yes        yes  20  20

In [8]:
x

school sex  age      Mjob      Fjob higher activities  G1  G2
0       GP   F   18   at_home   teacher    yes         no   5   6
1       GP   F   17   at_home     other    yes         no   5   5
2       GP   F   15   at_home     other    yes         no   7   8
3       GP   F   15    health  services    yes        yes  15  14
4       GP   F   16     other     other    yes         no   6  10
..     ...  ..  ...       ...       ...    ...        ...  ..  ..
390     MS   M   20  services  services    yes         no   9   9
391     MS   M   17  services  services    yes         no  14  16
392     MS   M   21     other     other    yes         no  10   8
393     MS   M   18  services     other    yes         no  11  12
394     MS   M   19     other   at_home    yes         no   8   9

[395 rows x 9 columns]

In [9]:
x_new = x.append(new_student)
x_new

school sex  age      Mjob      Fjob higher activities  G1  G2
0       GP   F   18   at_home   teacher    yes         no   5   6
1       GP   F   17   at_home     other    yes         no   5   5
2       GP   F   15   at_home     other    yes         no   7   8
3       GP   F   15    health  services    yes        yes  15  14
4       GP   F   16     other     other    yes         no   6  10
..     ...  ..  ...       ...       ...    ...        ...  ..  ..
391     MS   M   17  services  services    yes         no  14  16
392     MS   M   21     other     other    yes         no  10   8
393     MS   M   18  services     other    yes         no  11  12
394     MS   M   19     other   at_home    yes         no   8   9
0       GP   M   25   teacher  services    yes        yes  20  20

[396 rows x 9 columns]

In [10]:
x_new.iloc[-1]

school              GP
sex                  M
age                 25
Mjob           teacher
Fjob          services
higher             yes
activities         yes
G1                  20
G2                  20
Name: 0, dtype: object

In [11]:
dummy_matrices(x_new)

C:\Users\Admin\Desktop\Project\my_functions.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_num[column] = non_num[column].apply(lambda x: column[0].lower() + "_" + x)


school  sex  age  higher  activities  G1  G2  m_at_home  m_health  \
0         0    0   18       1           0   5   6          1         0   
1         0    0   17       1           0   5   5          1         0   
2         0    0   15       1           0   7   8          1         0   
3         0    0   15       1           1  15  14          0         1   
4         0    0   16       1           0   6  10          0         0   
..      ...  ...  ...     ...         ...  ..  ..        ...       ...   
391       1    1   17       1           0  14  16          0         0   
392       1    1   21       1           0  10   8          0         0   
393       1    1   18       1           0  11  12          0         0   
394       1    1   19       1           0   8   9          0         0   
0         0    1   25       1           1  20  20          0         0   

     m_other  m_services  f_at_home  f_health  f_other  f_services  
0          0           0          0         0        0           0  
1          0           0          0         0        1           0  
2          0           0          0         0        1           0  
3          0           0          0         0        0           1  
4          1           0          0         0        1           0  
..       ...         ...        ...       ...      ...         ...  
391        0           1          0         0        0           1  
392        1           0          0         0        1           0  
393        0           1          0         0        1           0  
394        1           0          1         0        0           0  
0          0           0          0         0        0           1  

[396 rows x 15 columns]

In [12]:
dummy_matrices(x_new).iloc[-1]

C:\Users\Admin\Desktop\Project\my_functions.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_num[column] = non_num[column].apply(lambda x: column[0].lower() + "_" + x)


school         0
sex            1
age           25
higher         1
activities     1
G1            20
G2            20
m_at_home      0
m_health       0
m_other        0
m_services     0
f_at_home      0
f_health       0
f_other        0
f_services     1
Name: 0, dtype: int64

In [13]:
def dummy_matrix_of_new_student(new_student, x):
    """
    Turns categoraical features of a new student into dummy matrices.
    
    Parameters:
        new_student (pandas dataframe): A new student array with categorical features
                  x (pandas dataframe): Training set as DataFrame
        
    Returns:
        new_student_dummy (pandas dataframe): The new student array with dummy matrices
    """
    
    x_new = x.append(new_student)
    new_dummy = dummy_matrices(x_new)
    new_student_dummy = new_dummy.iloc[-1]
    
    return new_student_dummy
    

In [14]:
dummy_matrix_of_new_student(new_student, x)

school         0
sex            1
age           25
higher         1
activities     1
G1            20
G2            20
m_at_home      0
m_health       0
m_other        0
m_services     0
f_at_home      0
f_health       0
f_other        0
f_services     1
Name: 0, dtype: int64

In [14]:
new_example = dummy_matrix_of_new_student(new_student, x)
new_example

TypeError: cannot concatenate object of type '<class 'function'>'; only Series and DataFrame objs are valid

In [2]:
x, y = load_data("data/student-mat.csv")

In [3]:
x_dummy = dummy_matrices(x)
x_dummy

C:\Users\Admin\Desktop\Project\my_functions.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_num[column] = non_num[column].apply(lambda x: column[0].lower() + "_" + x)


school  sex  age  higher  activities  G1  G2  m_at_home  m_health  \
0         0    0   18       1           0   5   6          1         0   
1         0    0   17       1           0   5   5          1         0   
2         0    0   15       1           0   7   8          1         0   
3         0    0   15       1           1  15  14          0         1   
4         0    0   16       1           0   6  10          0         0   
..      ...  ...  ...     ...         ...  ..  ..        ...       ...   
390       1    1   20       1           0   9   9          0         0   
391       1    1   17       1           0  14  16          0         0   
392       1    1   21       1           0  10   8          0         0   
393       1    1   18       1           0  11  12          0         0   
394       1    1   19       1           0   8   9          0         0   

     m_other  m_services  m_teacher  f_at_home  f_health  f_other  f_services  \
0          0           0          0          0         0        0           0   
1          0           0          0          0         0        1           0   
2          0           0          0          0         0        1           0   
3          0           0          0          0         0        0           1   
4          1           0          0          0         0        1           0   
..       ...         ...        ...        ...       ...      ...         ...   
390        0           1          0          0         0        0           1   
391        0           1          0          0         0        0           1   
392        1           0          0          0         0        1           0   
393        0           1          0          0         0        1           0   
394        1           0          0          1         0        0           0   

     f_teacher  
0            1  
1            0  
2            0  
3            0  
4            0  
..         ...  
390          0  
391          0  
392          0  
393          0  
394          0  

[395 rows x 17 columns]

In [4]:
x_dummy_np = pd_to_np(x_dummy)
y_np = pd_to_np(y)

In [5]:
x_dummy_np

array([[ 0.,  0., 18., ...,  0.,  0.,  1.],
       [ 0.,  0., 17., ...,  1.,  0.,  0.],
       [ 0.,  0., 15., ...,  1.,  0.,  0.],
       ...,
       [ 1.,  1., 21., ...,  1.,  0.,  0.],
       [ 1.,  1., 18., ...,  1.,  0.,  0.],
       [ 1.,  1., 19., ...,  0.,  0.,  0.]])

In [6]:
y_np

array([ 6.,  6., 10., 15., 10., 15., 11.,  6., 19., 15.,  9., 12., 14.,
       11., 16., 14., 14., 10.,  5., 10., 15., 15., 16., 12.,  8.,  8.,
       11., 15., 11., 11., 12., 17., 16., 12., 15.,  6., 18., 15., 11.,
       13., 11., 12., 18., 11.,  9.,  6., 11., 20., 14.,  7., 13., 13.,
       10., 11., 13., 10., 15., 15.,  9., 16., 11., 11.,  9.,  9., 10.,
       15., 12.,  6.,  8., 16., 15., 10.,  5., 14., 11., 10., 10., 11.,
       10.,  5., 12., 11.,  6., 15., 10.,  8.,  6., 14., 10.,  7.,  8.,
       18.,  6., 10., 14., 10., 15., 10., 14.,  8.,  5., 17., 14.,  6.,
       18., 11.,  8., 18., 13., 16., 19., 10., 13., 19.,  9., 16., 14.,
       13.,  8., 13., 15., 15., 13., 13.,  8., 12., 11.,  9.,  0., 18.,
        0.,  0., 12., 11.,  0.,  0.,  0.,  0., 12., 15.,  0.,  9., 11.,
       13.,  0., 11.,  0., 11.,  0., 10.,  0., 14., 10.,  0., 12.,  8.,
       13., 10., 15., 12.,  0.,  7.,  0., 10.,  7., 12., 10., 16.,  0.,
       14.,  0., 16., 10.,  0.,  9.,  9., 11.,  6.,  9., 11.,  8

In [7]:
x_dummy_np_norm = normalize(x_dummy_np)
x_dummy_np_norm

array([[0.        , 0.        , 0.81818182, ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.77272727, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.68181818, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 1.        , 0.95454545, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.81818182, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.86363636, ..., 0.        , 0.        ,
        0.        ]])

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x_dummy_np_norm, y_np, train_size=0.7)
x_train

array([[0.        , 0.        , 0.72727273, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.72727273, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.90909091, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.        , 1.        , 0.77272727, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.72727273, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.72727273, ..., 0.        , 1.        ,
        0.        ]])

In [9]:
w_pred, b_pred, r_sq = compute_model(x_train, y_train)

In [16]:
print(w_pred, "\n", "\n",  b_pred, "\n", "\n", r_sq)

[ 0.4116192   0.07902158 -5.38416819  0.33060769 -0.30360968  4.09610802
 18.18316817 -0.20180209 -0.11270923 -0.02432727  0.22639085  0.11244774
 -0.14341631  0.31330207  0.31448816 -0.1279009  -0.35647303] 
 
 1.3928310794655925 
 
 0.8180349517477998


In [11]:
b_pred

1.3928310794655925

In [12]:
r_sq

0.8180349517477998

In [13]:
y_pred = np.dot(w_pred,new_example) + b_pred

NameError: name 'new_example' is not defined

In [31]:
y_pred

293.0181668502155